name: 'Terrafir Plan Assessment'
description: 'Use Terrafir to assess the Terraform plan file for security vulnerabilities'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  apiKey: 
    description: 'API key for Terrafir'
    required: true
  email: 
    description: 'Email for Terrafir'
    required: true
outputs:
  time:
    description: 'The time plan was assessed' #TODO
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.apiKey }}
    - ${{ inputs.email }}